INSERT INTO `employee_basicinfos` (`id`, `user_id`, `empcode`, `basicinfo_placeofbirth`, `basicinfo_sex`, `basicinfo_civilstatus`, `basicinfo_citizenship`, `basicinfo_citizentype`, `basicinfo_height`, `basicinfo_weight`, `basicinfo_bloodtype`, `created_at`, `updated_at`, `deleted_at`) VALUES (NULL, '658', 'LAN009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `employee_addinfos` (`id`, `user_id`, `empcode`, `empcode_id`, `addinfo_pagibig`, `addinfo_philhealth`, `addinfo_sss`, `addinfo_tin`, `addinfo_gsis_id`, `addinfo_gsis_policy`, `addinfo_gsis_bp`, `addinfo_partner`, `addinfo_landbank`, `addinfo_atm`, `addinfo_gov`, `addinfo_gov_id`, `addinfo_gov_place_date`, `addinfo_ctc`, `addinfo_ctc_date`, `addinfo_ctc_place`, `created_at`, `updated_at`) VALUES (NULL, '658', 'LAN009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `employee_address_permanents` (`id`, `user_id`, `empcode`, `permanent_add_street`, `permanent_add_subd`, `permanent_add_brgy`, `permanent_add_no`, `permanent_add_mun`, `permanent_add_prov`, `permanent_add_zipcode`, `created_at`, `updated_at`) VALUES (NULL, '658', 'LAP009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `employee_address_residentials` (`id`, `user_id`, `empcode`, `residential_add_street`, `residential_add_subd`, `residential_add_brgy`, `residential_add_no`, `residential_add_mun`, `residential_add_prov`, `residential_add_zipcode`, `created_at`, `updated_at`) VALUES (NULL, '658', 'LAN009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `employee_contacts` (`id`, `user_id`, `empcode`, `contact_residential`, `contact_permanent`, `contact_cellnum`, `created_at`, `updated_at`, `deleted_at`) VALUES (NULL, '658', 'LAN009', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `employee_families` (`id`, `user_id`, `empcode`, `fam_spouse_lname`, `fam_spouse_fname`, `fam_spouse_mname`, `fam_spouse_exname`, `fam_spouse_occ`, `fam_spouse_emp`, `fam_spouse_emp_add`, `fam_spouse_tel`, `fam_father_lname`, `fam_father_fname`, `fam_father_mname`, `fam_father_exname`, `fam_mother_maiden`, `fam_mother_lname`, `fam_mother_fname`, `fam_mother_mname`, `created_at`, `updated_at`) VALUES (NULL, '658', 'LAN009', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);